#!/usr/bin/env bash
#
# deploy.sh — local container-pool rig for the catalog example app.
#
# Builds the catalog app into a Docker image and runs N replicas behind an APISIX
# round-robin upstream, so you can exercise concurrency / load balancing locally.
# Postgres comes from the base compose.yaml (./profile.sh up); APISIX + etcd come from
# infra/compose.apisix.yaml. No auth in this phase — that's intentional.
#
# Topology:
#   client -> APISIX :9085 (round-robin) -> catalog-1..N (host ports 28081..2808N) -> Postgres
#   (host 9085 not 9080 — podman-machine's gvproxy holds :9080 on this host)
#
# Usage:
#   ./deploy.sh up [--pods N]     Build (if needed) + start Postgres, APISIX, and N app pods,
#                                 then point the APISIX upstream at all pods. Default N=2.
#   ./deploy.sh down [-v]         Stop app pods + APISIX (keep Postgres). -v also removes volumes.
#   ./deploy.sh build             Rebuild the app image only.
#   ./deploy.sh scale --pods N    Re-generate + restart the pool at N pods, resync upstream.
#   ./deploy.sh status            Show what's running + the current upstream node set.
#   ./deploy.sh logs [--pod K]    Tail all app pods, or one.
#
# Pod count is remembered in build/.deploy.state across up/down.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT="opa-abac-example"
APP_DIR="$SCRIPT_DIR/example-catalog-management-service"
APISIX_COMPOSE="$SCRIPT_DIR/infra/compose.apisix.yaml"
JAEGER_COMPOSE="$SCRIPT_DIR/infra/compose.jaeger.yaml"
OPA_COMPOSE="$SCRIPT_DIR/infra/compose.opa.yaml"
KEYCLOAK_COMPOSE="$SCRIPT_DIR/infra/compose.keycloak.yaml"
GEN_COMPOSE="$SCRIPT_DIR/build/compose.pods.generated.yaml"
STATE_FILE="$SCRIPT_DIR/build/.deploy.state"
IMAGE="opa-abac-catalog:local"

# Feature toggles. Tracing + OPA on by default (Phase B). OIDC off by default — opt in with
# ENABLE_OIDC=1 ./deploy.sh up  (Phase 2 gateway auth; needs Keycloak, slower to start).
ENABLE_TRACING="${ENABLE_TRACING:-1}"
ENABLE_OPA="${ENABLE_OPA:-1}"
ENABLE_OIDC="${ENABLE_OIDC:-0}"

APISIX_ADMIN="${APISIX_ADMIN:-http://localhost:9180}"
API_KEY="${APISIX_API_KEY:-edd1c9f034335f136f87ad84b625c8f1}"

# pod K publishes on BASE_PORT+K (28081, 28082, …). Base 28080 (not the portal's 18080
# range) so this rig never collides with a running portal podman-machine on 18081/18082.
BASE_PORT=28080

# --- arg parsing ------------------------------------------------------------
CMD="${1:-help}"; shift || true
PODS=""; POD_INDEX=""; DOWN_ARGS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --pods) PODS="$2"; shift 2 ;;
    --pod)  POD_INDEX="$2"; shift 2 ;;
    -v)     DOWN_ARGS+=("-v"); shift ;;
    *)      shift ;;
  esac
done

save_pods() { mkdir -p "$(dirname "$STATE_FILE")"; echo "PODS=$1" > "$STATE_FILE"; }
resolve_pods() {
  if [ -n "$PODS" ]; then echo "$PODS"; return; fi
  if [ -f "$STATE_FILE" ]; then grep -E '^PODS=' "$STATE_FILE" | cut -d= -f2; return; fi
  echo "2"
}

# --- image build ------------------------------------------------------------
build_image() {
  echo "==> Building app image $IMAGE (Gradle bootJar inside the image)..."
  # Build context is the repo root so the multi-module Gradle build can see the libraries.
  docker build -t "$IMAGE" -f "$APP_DIR/Dockerfile" "$SCRIPT_DIR"
}

image_exists() { docker image inspect "$IMAGE" >/dev/null 2>&1; }

# --- multi-pod compose generation ------------------------------------------
# Pod K: container catalog-K, published host port BASE_PORT+K -> 8080.
# All pods talk to the Postgres container by its compose DNS name (opa-abac-postgres).
generate_compose() {
  local n="$1"
  mkdir -p "$(dirname "$GEN_COMPOSE")"
  {
    cat <<HEADER
# Auto-generated by deploy.sh — do not edit. Regenerated on every up/scale.
name: $PROJECT

services:
HEADER
    # When tracing is on, prepend the OTEL Java agent (baked into the image). Computed
    # per-pod inside the loop (each pod gets its own pod.name resource attribute).
    local java_opts="-Xms256m -Xmx512m -XX:+UseG1GC"
    [ "$ENABLE_TRACING" = "1" ] && java_opts="-javaagent:/opt/otel/agent.jar $java_opts"

    for i in $(seq 1 "$n"); do
      local host_port=$((BASE_PORT + i))
      # ABAC enforcement in the app. Only enabled when OIDC is on — without a forwarded token there is
      # no subject to authorize, so every request would (correctly) fail closed. The policy prefix is
      # empty: the per-type resolver posts to /v1/data/{catalog,category,product}.
      local abac_env=""
      if [ "$ENABLE_OIDC" = "1" ] && [ "$ENABLE_OPA" = "1" ]; then
        abac_env="      OPA_ABAC_ENABLED: \"true\"
      OPA_ABAC_BASE_URL: \"http://opa:8181\"
      OPA_ABAC_POLICY_PREFIX: \"\""
      else
        abac_env="      OPA_ABAC_ENABLED: \"false\""
      fi
      local otel_env=""
      if [ "$ENABLE_TRACING" = "1" ]; then
        otel_env="      OTEL_SERVICE_NAME: \"catalog-management-service\"
      OTEL_RESOURCE_ATTRIBUTES: \"pod.name=catalog-$i\"
      OTEL_EXPORTER_OTLP_ENDPOINT: \"http://opa-abac-jaeger:4318\"
      OTEL_EXPORTER_OTLP_PROTOCOL: \"http/protobuf\"
      OTEL_TRACES_SAMPLER: \"always_on\"
      OTEL_TRACES_EXPORTER: \"otlp\"
      OTEL_METRICS_EXPORTER: \"none\"
      OTEL_LOGS_EXPORTER: \"none\""
      fi
      cat <<POD
  catalog-$i:
    image: $IMAGE
    container_name: catalog-$i
    hostname: catalog-$i
    environment:
      SERVER_PORT: "8080"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://opa-abac-postgres:5432/catalog"
      SPRING_DATASOURCE_USERNAME: "catalog"
      SPRING_DATASOURCE_PASSWORD: "catalog"
      JAVA_OPTS: "$java_opts"
$abac_env
$otel_env
    ports:
      - "$host_port:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 40s

POD
    done
    # All three composes share project name "$PROJECT", so they share the auto-created
    # "${PROJECT}_default" network — pods reach opa-abac-postgres by DNS, no explicit network block.
  } > "$GEN_COMPOSE"
}

app_compose() { docker compose -p "$PROJECT" -f "$GEN_COMPOSE" "$@"; }
apisix_compose() { docker compose -p "$PROJECT" -f "$APISIX_COMPOSE" "$@"; }
jaeger_compose() { docker compose -p "$PROJECT" -f "$JAEGER_COMPOSE" "$@"; }
opa_compose() { docker compose -p "$PROJECT" -f "$OPA_COMPOSE" "$@"; }
keycloak_compose() { docker compose -p "$PROJECT" -f "$KEYCLOAK_COMPOSE" "$@"; }

# Wait for Keycloak's realm discovery doc to be served (import + boot can take 30-60s).
wait_keycloak() {
  echo "==> Waiting for Keycloak realm 'catalog-demo' to be ready..."
  local deadline=$(( SECONDS + 120 ))
  while (( SECONDS < deadline )); do
    if curl -sf -o /dev/null "http://localhost:28888/realms/catalog-demo/.well-known/openid-configuration" 2>/dev/null; then
      echo "   Keycloak realm ready."; return 0
    fi
    sleep 4
  done
  echo "   WARN: Keycloak realm not ready in time (route's openid-connect may 503 until it is)." >&2
  return 1
}

# --- APISIX upstream sync ---------------------------------------------------
# Republish catalog-pool to round-robin over the N running pods (host ports 18081..).
apisix_sync_upstream() {
  local n="$1"
  if ! curl -sf -o /dev/null -m 2 -H "X-API-KEY: $API_KEY" "$APISIX_ADMIN/apisix/admin/upstreams" 2>/dev/null; then
    echo "==> APISIX admin unreachable at $APISIX_ADMIN — skipping upstream sync"
    return 0
  fi
  local nodes="" i=1
  while [ "$i" -le "$n" ]; do
    local port=$((BASE_PORT + i))
    [ -n "$nodes" ] && nodes="$nodes,"
    nodes="$nodes\"host.docker.internal:$port\": 1"
    i=$((i + 1))
  done
  local payload
  payload=$(printf '{"type":"roundrobin","pass_host":"pass","scheme":"http","nodes":{%s}}' "$nodes")
  local code
  code=$(curl -s -o /dev/null -w "%{http_code}" -X PUT \
    -H "X-API-KEY: $API_KEY" -H "Content-Type: application/json" \
    -d "$payload" "$APISIX_ADMIN/apisix/admin/upstreams/catalog-pool")
  if [ "$code" = "200" ] || [ "$code" = "201" ]; then
    echo "==> APISIX catalog-pool -> round-robin over $n pod(s): $nodes"
  else
    echo "   WARN: upstream PUT returned $code (payload: $payload)" >&2
  fi
}

wait_pods_healthy() {
  local n="$1"
  echo "==> Waiting for $n app pod(s) to become healthy..."
  local deadline=$(( SECONDS + 180 ))
  while (( SECONDS < deadline )); do
    local up=0 i=1
    while [ "$i" -le "$n" ]; do
      if curl -sf "http://localhost:$((BASE_PORT + i))/actuator/health" 2>/dev/null | grep -q '"status":"UP"'; then
        up=$((up + 1))
      fi
      i=$((i + 1))
    done
    if [ "$up" -eq "$n" ]; then echo "   all $n pod(s) healthy."; return 0; fi
    sleep 3
  done
  echo "   WARN: not all pods became healthy in time." >&2
  return 1
}

require_postgres() {
  if ! docker ps --format '{{.Names}}' | grep -q '^opa-abac-postgres$'; then
    echo "ERROR: Postgres not running. Start base infra first: ./profile.sh up" >&2
    exit 1
  fi
}

# --- commands ---------------------------------------------------------------
case "$CMD" in
  build)
    build_image
    ;;

  up)
    n="$(resolve_pods)"; save_pods "$n"
    require_postgres
    image_exists || build_image
    if [ "$ENABLE_TRACING" = "1" ]; then
      echo "==> Starting Jaeger (traces)..."; jaeger_compose up -d
    fi
    if [ "$ENABLE_OPA" = "1" ]; then
      echo "==> Starting OPA (allow-all policy)..."; opa_compose up -d
    fi
    if [ "$ENABLE_OIDC" = "1" ]; then
      echo "==> Starting Keycloak (realm import)..."; keycloak_compose up -d
    fi
    echo "==> Starting APISIX + etcd..."
    apisix_compose up -d
    generate_compose "$n"
    echo "==> Starting $n app pod(s)..."
    app_compose up -d
    wait_pods_healthy "$n" || true
    # OIDC route needs Keycloak's discovery doc reachable before APISIX validates tokens.
    [ "$ENABLE_OIDC" = "1" ] && wait_keycloak || true
    # Seed route (idempotent) then sync upstream to the real pod set.
    ENABLE_OIDC="$ENABLE_OIDC" ENABLE_TRACING="$ENABLE_TRACING" ENABLE_OPA="$ENABLE_OPA" \
      APISIX_ADMIN="$APISIX_ADMIN" APISIX_API_KEY="$API_KEY" \
      bash "$SCRIPT_DIR/infra/apisix/init-routes.sh"
    apisix_sync_upstream "$n"
    echo ""
    echo "==> Up. Gateway: http://localhost:9085   (e.g. curl http://localhost:9085/actuator/health)"
    [ "$ENABLE_TRACING" = "1" ] && echo "    Jaeger UI: http://localhost:26686"
    [ "$ENABLE_OPA" = "1" ] && echo "    OPA:       http://localhost:28181  (allow-all gateway policy)"
    [ "$ENABLE_OIDC" = "1" ] && echo "    Keycloak:  http://localhost:28888  (admin/admin; realm catalog-demo, user demo/demo)"
    for i in $(seq 1 "$n"); do echo "    catalog-$i -> http://localhost:$((BASE_PORT + i))"; done
    ;;

  scale)
    n="$(resolve_pods)"; save_pods "$n"
    require_postgres
    image_exists || build_image
    generate_compose "$n"
    app_compose up -d --remove-orphans
    wait_pods_healthy "$n" || true
    apisix_sync_upstream "$n"
    ;;

  down)
    if [ -f "$GEN_COMPOSE" ]; then app_compose down "${DOWN_ARGS[@]+"${DOWN_ARGS[@]}"}" || true; fi
    apisix_compose down "${DOWN_ARGS[@]+"${DOWN_ARGS[@]}"}" || true
    opa_compose down "${DOWN_ARGS[@]+"${DOWN_ARGS[@]}"}" || true
    keycloak_compose down "${DOWN_ARGS[@]+"${DOWN_ARGS[@]}"}" || true
    jaeger_compose down "${DOWN_ARGS[@]+"${DOWN_ARGS[@]}"}" || true
    echo "==> Pool + APISIX + OPA + Keycloak + Jaeger down. (Postgres left running — ./profile.sh down to stop it.)"
    ;;

  status)
    echo "=== containers ==="
    docker ps --filter "name=catalog-" --filter "name=opa-abac-" \
      --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'
    echo "=== APISIX upstream catalog-pool ==="
    curl -s -H "X-API-KEY: $API_KEY" "$APISIX_ADMIN/apisix/admin/upstreams/catalog-pool" 2>/dev/null \
      | grep -o '"nodes":{[^}]*}' || echo "(unreachable)"
    ;;

  logs)
    n="$(resolve_pods)"
    if [ -n "$POD_INDEX" ]; then
      docker logs -f "catalog-$POD_INDEX"
    else
      app_compose logs -f
    fi
    ;;

  *)
    grep -E '^#( |$)' "$0" | sed -E 's/^# ?//'
    exit 1
    ;;
esac
